// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epbfymygczpztsjzmowh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwYmZ5bXlnY3pwenRzanptb3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5ODg0NzksImV4cCI6MjA2NjU2NDQ3OX0.oP9TxtFMP303ygiAM6yQF4TtDqHgFe39jd0mtldb4BM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);